/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeEntriesRouteImport } from './routes/time-entries'
import { Route as IndexRouteImport } from './routes/index'

const TimeEntriesRoute = TimeEntriesRouteImport.update({
  id: '/time-entries',
  path: '/time-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/time-entries': typeof TimeEntriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/time-entries': typeof TimeEntriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/time-entries': typeof TimeEntriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/time-entries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/time-entries'
  id: '__root__' | '/' | '/time-entries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimeEntriesRoute: typeof TimeEntriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time-entries': {
      id: '/time-entries'
      path: '/time-entries'
      fullPath: '/time-entries'
      preLoaderRoute: typeof TimeEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimeEntriesRoute: TimeEntriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
